import type { Metadata } from 'next'
import Link from 'next/link'
import { verifyStatCardSignature } from '@/lib/stats'
import { buttonVariants } from '@/components/ui/button'

// The rich-unfurl counterpart to app/api/stat-card/route.tsx's raw PNG — see
// buildStatCardShareUrl()'s doc comment in lib/stats.ts for why this exists
// (a bare image link doesn't unfurl as a preview card on iMessage/X/
// LinkedIn; this page wraps it in real og:image/twitter:card metadata so it
// does). Public by design, same as the image route: the signature is what's
// trusted here, not a session — anyone with a validly-signed link (which
// only the dashboard page, itself behind a session, can produce) can view
// it, which is the whole point of something meant to be shared.

type SearchParams = Promise<Record<string, string | string[] | undefined>>

function toURLSearchParams(sp: Record<string, string | string[] | undefined>): URLSearchParams {
  const params = new URLSearchParams()
  for (const [key, value] of Object.entries(sp)) {
    if (typeof value === 'string') params.set(key, value)
    else if (Array.isArray(value) && value.length > 0) params.set(key, value[0])
  }
  return params
}

export async function generateMetadata({ searchParams }: { searchParams: SearchParams }): Promise<Metadata> {
  const params = toURLSearchParams(await searchParams)
  if (!verifyStatCardSignature(params)) {
    return { title: 'Invalid share link — Meminno' }
  }

  const imagePath = `/api/stat-card?${params.toString()}`
  return {
    title: 'My Meminno weekly stat card',
    description: 'A shareable weekly recap of Meminno study activity.',
    openGraph: {
      title: 'My Meminno weekly stat card',
      description: 'A shareable weekly recap of Meminno study activity.',
      images: [{ url: imagePath, width: 1200, height: 630 }],
    },
    twitter: {
      card: 'summary_large_image',
      images: [imagePath],
    },
  }
}

export default async function SharedStatCardPage({ searchParams }: { searchParams: SearchParams }) {
  const params = toURLSearchParams(await searchParams)

  if (!verifyStatCardSignature(params)) {
    return (
      <main className="flex min-h-screen flex-col items-center justify-center gap-4 p-8 text-center">
        <h1 className="text-2xl font-semibold">This share link isn&apos;t valid</h1>
        <p className="max-w-md text-muted-foreground">
          It may have been altered, or it wasn&apos;t generated by Meminno. Head back home to get your own.
        </p>
        <Link href="/" className={buttonVariants()}>
          Back home
        </Link>
      </main>
    )
  }

  const imagePath = `/api/stat-card?${params.toString()}`

  return (
    <main className="flex min-h-screen flex-col items-center justify-center gap-6 p-8">
      {/* eslint-disable-next-line @next/next/no-img-element -- this is already a fully-rendered 1200x630 PNG
          from our own dynamic route, not a static asset for next/image to optimize/reprocess. */}
      <img src={imagePath} alt="Meminno weekly stat card" className="w-full max-w-2xl rounded-3xl shadow-xl" />
      <Link href="/" className={buttonVariants({ size: 'lg' })}>
        Get your own Meminno stat card
      </Link>
    </main>
  )
}
